#pragma once
#include <QPalette>

inline QPalette defaultPalette;

inline void initDefaultPalette() {
    defaultPalette = QPalette();
    // Generated by Claude
    // Main backgrounds
    defaultPalette.setColor(QPalette::Window, QColor(30, 30, 30));           // Main background
    defaultPalette.setColor(QPalette::Base, QColor(25, 25, 25));             // Input fields background
    defaultPalette.setColor(QPalette::AlternateBase, QColor(40, 40, 40));    // Alternate rows

    // Text colors
    defaultPalette.setColor(QPalette::WindowText, QColor(220, 220, 220));    // Main text
    defaultPalette.setColor(QPalette::Text, QColor(220, 220, 220));          // Input text

    // Button colors
    defaultPalette.setColor(QPalette::Button, QColor(30, 30, 30));           // Button background
    defaultPalette.setColor(QPalette::ButtonText, QColor(220, 220, 220));    // Button text

    // Selection colors
    defaultPalette.setColor(QPalette::Highlight, QColor(60, 60, 60));        // Selection background (subtle)
    defaultPalette.setColor(QPalette::HighlightedText, Qt::white);           // Selected text

    // Disabled state
    // defaultPalette.setColor(QPalette::Disabled, QPalette::WindowText, QColor(100, 100, 100));
    // defaultPalette.setColor(QPalette::Disabled, QPalette::Text, QColor(100, 100, 100));
    // defaultPalette.setColor(QPalette::Disabled, QPalette::ButtonText, QColor(100, 100, 100));

    // Borders/shadows - keeping them subtle and flat
    // defaultPalette.setColor(QPalette::Light, QColor(50, 50, 50));
    // defaultPalette.setColor(QPalette::Midlight, QColor(45, 45, 45));
    // defaultPalette.setColor(QPalette::Dark, QColor(20, 20, 20));
    // defaultPalette.setColor(QPalette::Mid, QColor(30, 30, 30));
    // defaultPalette.setColor(QPalette::Shadow, QColor(10, 10, 10));
}